version: '3.7'

services:

  react-material-dashboard:
    container_name: react-material-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true